spring:
    datasource:
        dynamic:
            # 默认数据源
            primary: master
            # 设置严格模式（不使用默认）
            strict: true
            datasource:
                common:
                    url: jdbc:mysql://gjfleo.top:3306/common
                    username: root
                    password: Liger12311231
                lol:
                    url: jdbc:mysql://gjfleo.top:3306/lol
                    username: root
                    password: Liger12311231