spring:
    servlet:
        multipart:
            # 上传文件的大小
            max-file-size: 100MB
            # 请求的大小
            max-request-size: 100MB

    datasource:
        dynamic:
            # 默认数据源
            primary: master
            # 设置严格模式（不使用默认）
            strict: true
            datasource:
                common:
                    url: jdbc:mysql://gjfleo.top:3306/common?characterEncoding=UTF-8
                    username: root
                    password: Liger12311231
                lol:
                    url: jdbc:mysql://gjfleo.top:3306/lol?characterEncoding=UTF-8
                    username: root
                    password: Liger12311231