spring:
    servlet:
        multipart:
            # 上传文件的大小
            max-file-size: 100MB
            # 请求的大小
            max-request-size: 100MB

    datasource:
        dynamic:
            # 默认数据源
            primary: db
            # 设置严格模式（不使用默认）
            strict: false
            datasource:
                db:
                    url: jdbc:mysql://gjfleo.top:3306/db?characterEncoding=UTF-8
                    username: root
                    password: Liger12311231

    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml